# Generated by Django 5.1.5 on 2026-08-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='declared_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Hech narsa bilmayman'), ('elementary', 'Elementary — oddiy gaplar'), ('intermediate', 'Intermediate — suhbat quraman'), ('advanced', 'Advanced — erkin gapiraman')], default='', help_text="O'quvchi o'zi aytgan daraja. Kontentga ta'sir qilmaydi", max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_background',
            field=models.TextField(blank=True, default='', help_text="Nimalarni biladi, qayerda o'rgangan — o'z so'zlari bilan"),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='placement_done',
            field=models.BooleanField(default=False),
        ),
    ]
