# Generated by Django 5.1.5 on 2026-08-11 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Yopiq'), ('active', 'Ochiq'), ('mastered', "O'zlashtirilgan")], default='locked', max_length=16)),
                ('sessions_count', models.IntegerField(default=0)),
                ('last_accuracy', models.FloatField(blank=True, null=True)),
                ('best_accuracy', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mavzu progressi',
                'verbose_name_plural': 'Mavzu progresslari',
                'db_table': 'topic_progress',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_structure', models.CharField(blank=True, default='', max_length=64)),
                ('error_type', models.CharField(blank=True, default='', max_length=64)),
                ('learner_utterance', models.TextField(blank=True, default='')),
                ('correction', models.TextField(blank=True, default='')),
                ('review_count', models.IntegerField(default=0)),
                ('next_review_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='practice.session')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='content.topic')),
            ],
            options={
                'verbose_name': 'Xato yozuvi',
                'verbose_name_plural': 'Xato yozuvlari',
                'db_table': 'error_logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
