# Generated by Django 5.1.5 on 2026-08-11 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('order', models.IntegerField()),
                ('default_mode', models.CharField(choices=[('repeat_drill', 'Repeat drill (A0)'), ('anticipation_drill', 'Anticipation drill (A1)'), ('speed_drill', 'Speed drill (A2)'), ('guided_conversation', 'Guided conversation (B1)'), ('free_conversation', 'Free conversation (B2)')], default='anticipation_drill', max_length=32)),
                ('title_uz', models.CharField(blank=True, default='', max_length=64)),
                ('description_uz', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Daraja',
                'verbose_name_plural': 'Darajalar',
                'db_table': 'levels',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title_uz', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, default='', max_length=200)),
                ('target_structure', models.CharField(help_text="Mashina o'qiy oladigan label, masalan past_simple_affirmative", max_length=64)),
                ('session_mode', models.CharField(blank=True, choices=[('repeat_drill', 'Repeat drill (A0)'), ('anticipation_drill', 'Anticipation drill (A1)'), ('speed_drill', 'Speed drill (A2)'), ('guided_conversation', 'Guided conversation (B1)'), ('free_conversation', 'Free conversation (B2)')], default='', help_text="Bo'sh bo'lsa darajaning default_mode qiymati ishlatiladi", max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan')], default='draft', max_length=16)),
                ('max_questions', models.IntegerField(default=10)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.level')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'db_table': 'topics',
                'ordering': ('level__order', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('question_text', models.TextField()),
                ('canonical_answer', models.TextField()),
                ('answer_variants', models.JSONField(blank=True, default=list)),
                ('elicitation_note', models.TextField(blank=True, default='', help_text="AI'ga ko'rsatma: target strukturani qanday majburlash kerak")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='draft', max_length=16)),
                ('source', models.CharField(choices=[('generated', 'Generatsiya qilingan'), ('manual', "Qo'lda")], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.topic')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'db_table': 'questions',
                'ordering': ('topic', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_uz', models.TextField(help_text="Maksimum 2 gap, o'zbekcha")),
                ('examples', models.JSONField(default=list, help_text='[{"en": "...", "uz": "..."}] — 3–4 ta misol')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='content.topic')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('translation_uz', models.CharField(max_length=200)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content.topic')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunklar',
                'db_table': 'chunks',
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('level', 'order'), name='uniq_level_order'),
        ),
    ]
