# Generated by Django 5.1.5 on 2026-08-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='default_mode',
            field=models.CharField(choices=[('repeat_drill', 'Repeat drill (A0)'), ('anticipation_drill', 'Anticipation drill (A1)'), ('speed_drill', 'Speed drill (A2)'), ('guided_conversation', 'Guided conversation (B1)'), ('free_conversation', 'Free conversation (B2)'), ('adaptive_conversation', 'Adaptive conversation (erkin suhbat)')], default='anticipation_drill', max_length=32),
        ),
        migrations.AlterField(
            model_name='topic',
            name='session_mode',
            field=models.CharField(blank=True, choices=[('repeat_drill', 'Repeat drill (A0)'), ('anticipation_drill', 'Anticipation drill (A1)'), ('speed_drill', 'Speed drill (A2)'), ('guided_conversation', 'Guided conversation (B1)'), ('free_conversation', 'Free conversation (B2)'), ('adaptive_conversation', 'Adaptive conversation (erkin suhbat)')], default='', help_text="Bo'sh bo'lsa darajaning default_mode qiymati ishlatiladi", max_length=32),
        ),
    ]
