# Generated by Django 5.1.5 on 2026-08-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='translation_ru',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='material',
            name='rule_ru',
            field=models.TextField(blank=True, default='', help_text='Ruscha variant'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='examples',
            field=models.JSONField(default=list, help_text='[{"en": "...", "uz": "...", "ru": "..."}] — 3–4 ta misol'),
        ),
    ]
