# Generated by Django 5.1.5 on 2026-08-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content_russian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='target_structure',
            field=models.CharField(help_text="Mashina o'qiy oladigan label, masalan past_simple_affirmative", max_length=64, unique=True),
        ),
    ]
