# Generated by Django 5.1.5 on 2026-08-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_topic_structure_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('track', 'order'), 'verbose_name': 'Mavzu', 'verbose_name_plural': 'Mavzular'},
        ),
        migrations.AddField(
            model_name='material',
            name='usage_ru',
            field=models.TextField(blank=True, default='', help_text='Ruscha variant'),
        ),
        migrations.AddField(
            model_name='material',
            name='usage_uz',
            field=models.TextField(blank=True, default='', help_text='Qayerda va qanday vaziyatda ishlatiladi (asosan iboralar uchun)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='focus_phrase',
            field=models.CharField(blank=True, default='', help_text='Faqat iboralar yo\'nalishi uchun: o\'quvchi aytishi kerak bo\'lgan aynan o\'sha ibora, masalan "look forward to + -ing"', max_length=120),
        ),
        migrations.AddField(
            model_name='topic',
            name='related_topic',
            field=models.ForeignKey(blank=True, help_text='Ibora qaysi grammatik mavzuga tayanadi (ixtiyoriy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_phrases', to='content.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='track',
            field=models.CharField(choices=[('grammar', 'Grammatika'), ('phrases', 'Iboralar')], db_index=True, default='grammar', help_text="Yo'nalish: grammatika yoki iboralar", max_length=16),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('track', 'order'), name='uniq_track_order'),
        ),
    ]
