# Generated by Django 5.1.5 on 2026-08-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_topic_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='related_topics',
            field=models.ManyToManyField(blank=True, help_text='Bu mavzu qaysi mavzularga tayanadi (grammatika, ibora)', related_name='linked_from', to='content.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='session_mode',
            field=models.CharField(blank=True, choices=[('repeat_drill', 'Repeat drill (A0)'), ('anticipation_drill', 'Anticipation drill (A1)'), ('speed_drill', 'Speed drill (A2)'), ('guided_conversation', 'Guided conversation (B1)'), ('free_conversation', 'Free conversation (B2)'), ('adaptive_conversation', 'Adaptive conversation (erkin suhbat)'), ('shadowing', 'Shadowing (ketidan takrorlash)'), ('roleplay', 'Rol suhbat (vaziyat)')], default='', help_text="Bo'sh bo'lsa adaptive_conversation ishlatiladi", max_length=32),
        ),
        migrations.AlterField(
            model_name='topic',
            name='track',
            field=models.CharField(choices=[('grammar', 'Grammatika'), ('phrases', 'Iboralar'), ('shadowing', 'Shadowing'), ('roleplay', 'Rol suhbat')], db_index=True, default='grammar', help_text="Yo'nalish: grammatika, iboralar, shadowing yoki rol suhbat", max_length=16),
        ),
    ]
