# Generated by Django 5.1.5 on 2026-08-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_topic_related_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='clip_end_ms',
            field=models.IntegerField(blank=True, help_text='Videoda tugash (ms)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='clip_start_ms',
            field=models.IntegerField(blank=True, help_text='Videoda boshlanish (ms)', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='ambience',
            field=models.CharField(blank=True, choices=[('none', "Yo'q"), ('cafe', 'Kafe'), ('street', "Ko'cha / mashina"), ('office', 'Ofis'), ('clinic', 'Poliklinika'), ('hotel', 'Mehmonxona qabulxonasi'), ('shop', "Do'kon")], default='', help_text='Klientdagi fon shovqini', max_length=16),
        ),
        migrations.AddField(
            model_name='topic',
            name='media_file',
            field=models.FileField(blank=True, help_text='Shadowing videosi (yuklangan fayl)', null=True, upload_to='shadowing/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='media_url',
            field=models.CharField(blank=True, default='', help_text='Shadowing videosi (tashqi manzil). Yuklangan fayl ustun turadi', max_length=500),
        ),
        migrations.AddField(
            model_name='topic',
            name='persona_en',
            field=models.CharField(blank=True, default='', help_text='AI kim bo\'ladi, masalan "Rustam, a busy waiter"', max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='setting_en',
            field=models.CharField(blank=True, default='', help_text='Vaziyat, masalan "lunch rush, every table full"', max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='voice',
            field=models.CharField(blank=True, default='', help_text="Gemini ovozi (bo'sh bo'lsa umumiy sozlama)", max_length=32),
        ),
    ]
