# Generated by Django 5.1.5 on 2026-08-11 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=32)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('completed', 'Yakunlangan'), ('time_limit', 'Vaqt limiti'), ('disconnect', 'Uzilish'), ('error', 'Xato')], default='', max_length=16)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('time_limit_seconds', models.IntegerField(default=300)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('processing', 'Qayta ishlanmoqda'), ('done', 'Tugallangan'), ('failed', 'Xato')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='content.topic')),
            ],
            options={
                'verbose_name': 'Sessiya',
                'verbose_name_plural': 'Sessiyalar',
                'db_table': 'sessions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SessionTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('speaker', models.CharField(choices=[('ai', 'AI'), ('learner', "O'quvchi")], max_length=8)),
                ('text', models.TextField(blank=True, default='')),
                ('started_at_ms', models.BigIntegerField(default=0)),
                ('ended_at_ms', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sessiya navbati',
                'verbose_name_plural': 'Sessiya navbatlari',
                'db_table': 'session_turns',
                'ordering': ('session', 'idx'),
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(default=1)),
                ('verdict', models.CharField(choices=[('correct', "To'g'ri"), ('incorrect', "Noto'g'ri"), ('off_topic', 'Mavzudan tashqari'), ('unintelligible', 'Tushunarsiz')], max_length=20)),
                ('target_structure_used', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, default='', max_length=64)),
                ('learner_utterance', models.TextField(blank=True, default='')),
                ('recovered_after_model', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='content.question')),
            ],
            options={
                'verbose_name': 'Baholash',
                'verbose_name_plural': 'Baholashlar',
                'db_table': 'evaluations',
                'ordering': ('session', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SessionMetrics',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='practice.session')),
                ('talk_time_seconds', models.IntegerField(default=0)),
                ('talk_time_pct', models.FloatField(default=0.0)),
                ('wpm', models.FloatField(default=0.0)),
                ('avg_response_latency_ms', models.IntegerField(default=0)),
                ('questions_total', models.IntegerField(default=0)),
                ('correct_total', models.IntegerField(default=0)),
                ('first_attempt_correct', models.IntegerField(default=0)),
                ('filler_count', models.IntegerField(default=0)),
                ('feedback_summary_uz', models.TextField(blank=True, default='')),
                ('errors', models.JSONField(blank=True, default=list)),
                ('analysis_ok', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sessiya metrikasi',
                'verbose_name_plural': 'Sessiya metrikalari',
                'db_table': 'session_metrics',
            },
        ),
    ]
