# Generated by Django 5.1.5 on 2026-08-11 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='practice.session'),
        ),
        migrations.AddField(
            model_name='sessionturn',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.question'),
        ),
        migrations.AddField(
            model_name='sessionturn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='practice.session'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-created_at'], name='idx_user_sessions'),
        ),
        migrations.AddConstraint(
            model_name='sessionturn',
            constraint=models.UniqueConstraint(fields=('session', 'idx'), name='uniq_session_turn_idx'),
        ),
    ]
